### ISSUE TITLE
Version since 1.3.0 is not valid for any KSP version on CKAN

### ISSUE THREAD

**Issue by MaximeBrean** [linuxgurugamer/MechJebForAll#5]
Hello,

As the title say, version from your adoption are no longer marked as compatible with any version of KSP (which should be in my opinion).
We then get version 1.2.0 from original author from CKAN (which is no longer compatible with KER).

Thanks :)

**Comment by linuxgurugamer** [comment]
According to CKAN on my local system, the max KSP version is:  any

If you are having problems with this, maybe bring it over to the CKAN thread.
